export { default as HomeTemplate } from './Home/Home'
export { default as AboutTemplate } from './About/About'
export { default as CareersTemplate } from './Careers/Careers'
export { default as GamesTemplate } from './Games/Games'
export { default as GameTemplate } from './Game/Game'
export { default as PrivacyTemplate } from './Privacy/Privacy'
export { default as SupportTemplate } from './Support/Support'
